### ISSUE TITLE
Unable to read cookie value if cookie name has a dot

### ISSUE THREAD

**Issue by burtek** [theodorejb/es-cookie#4]
This one works:

```javascript
const cookies = Cookies.getAll();
const access_token = cookies['test.AuthCookie'];
```

This one doesn't:

```javascript
const access_token = Cookies.get('test.AuthCookie'); // => undefined
```

**Comment by theodorejb** [comment]
I added a test for cookie names containing a period, and it successfully passes in the latest version of Firefox, Chrome, Edge, and Internet Explorer. It should be impossible for your first code block to work but the second to fail, since the `get` function just takes a `name` parameter and executes the following line:

```javascript
return getAll()[name];
```

**Comment by burtek** [comment]
It works now. Either some edge-case or mis-implementation. Thanks anyway
